kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: docker.ermo.space/mus
    registry: docker.ermo.space
    tags:
      - latest
      - dev
      - '1.0'

- name: deploy
  image: docker/compose
  volumes:
    - name: docker_socket
      path: /var/run/docker.sock
  commands:
    - docker-compose up -d

trigger:
  branch:
  - main

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock
