kind: pipeline
type: ssh
name: default

server:
  host: ermo.space
  user: root
  password:
    from_secret: password

steps:
- name: build
  commands:
  - cd /opt/docker/mus && git pull
  - cd .. && docker-compose up -d mus
