kind: pipeline
type: docker
name: default

steps:
- name: mus
  image: node:alpine
  commands:
  - npm install
  - npm run build
  - npm run start
  ports:
  - "3001:3000"
  labels:
  - traefik.enable=true
  - traefik.http.routers.mus.entrypoints=websecure
  - traefik.http.routers.mus.rule=Host(`drone.$DOMAIN`)
  - traefik.http.routers.mus.tls=true
  - traefik.http.routers.mus.tls.certresolver=le
