version: "3"
services:
  mus:
    container_name: mus
    image: docker.ermo.space/mus
    restart: unless-stopped
    ports:
      - 3005:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.mus.entrypoints=websecure
      - traefik.http.routers.mus.rule=Host(`mus.ermo.space`)
      - traefik.http.routers.mus.tls=true
      - traefik.http.routers.mus.tls.certresolver=le
      - traefik.docker.network=web
